export type VisualNoteImage = {
  alt: string;
  caption: string;
  height: number;
  id: string;
  src: string;
  title: string;
  width: number;
};

export type VisualNote = {
  articleSlug?: string;
  description: string;
  htmlGuideSrc?: string;
  htmlGuideTitle?: string;
  images: VisualNoteImage[];
  slug: string;
  title: string;
};

export const visualNotes: VisualNote[] = [
  {
    articleSlug: "agent-memory-survey",
    description: "把 agent memory 这篇综述整理成五张阅后复习图：领域地图、生命周期、检索与因果、评估工程落地，以及读后形成的个人理解。",
    htmlGuideSrc: "/visual-notes/agent-memory-survey/index.html",
    htmlGuideTitle: "HTML 阅后导览",
    slug: "agent-memory-survey",
    title: "Agent 记忆阅后图解",
    images: [
      {
        alt: "Agent memory 综述的领域地图图解，包含定义、解法、评测、工程落地和开放问题。",
        caption: "总览：这篇综述不只是解释 memory 定义，也把解法、benchmark、工程约束和开放问题整理成领域地图。",
        height: 1050,
        id: "overview",
        src: "/visual-notes/agent-memory-survey/01-overview.png",
        title: "01 综述是一张领域地图",
        width: 1500,
      },
      {
        alt: "Agent memory 的写入、管理、读取和反馈生命周期图。",
        caption: "生命周期：记忆不是被动档案，而是写入、管理、读取、行动反馈之间的状态管理循环。",
        height: 1050,
        id: "lifecycle",
        src: "/visual-notes/agent-memory-survey/02-lifecycle.png",
        title: "02 write-manage-read 生命周期",
        width: 1500,
      },
      {
        alt: "从语义相似检索走向因果依据检索的图解。",
        caption: "检索：RAG 的相似度只能回答“像什么”，长期 agent 还需要追踪“是什么导致了这个”。",
        height: 1050,
        id: "retrieval-causality",
        src: "/visual-notes/agent-memory-survey/03-retrieval-causality.png",
        title: "03 检索要从相似走向因果",
        width: 1500,
      },
      {
        alt: "Agent memory 评测指标、工程落地和治理约束的图解。",
        caption: "评估与工程：benchmark、写入过滤、读取成本、过期矛盾和治理约束共同决定记忆系统能否落地。",
        height: 1050,
        id: "evaluation-engineering",
        src: "/visual-notes/agent-memory-survey/04-evaluation-engineering.png",
        title: "04 benchmark 与工程落地",
        width: 1500,
      },
      {
        alt: "读完 agent memory 综述后的个人理解路径图。",
        caption: "阅后总结：从人类记忆类比转向目标相关的信息工程，并保留可反驳记忆、来源优先级和 Git-like 因果层这些判断。",
        height: 1050,
        id: "post-reading-summary",
        src: "/visual-notes/agent-memory-survey/05-post-reading-summary.png",
        title: "05 我的读后理解路径",
        width: 1500,
      },
    ],
  },
  {
    articleSlug: "defensive-programming-robustness",
    description: "把软件设计实践中正确性、健壮性、问题链条、RIP 模型、防御性编程工具和健壮性方法权衡整理成七张复习图。",
    slug: "defensive-programming-robustness",
    title: "通过防御性编程增强程序健壮性",
    images: [
      {
        alt: "防御性编程增强程序健壮性总览图，展示外部不确定性、问题链条、RIP 模型、防御工具和边界隔栏。",
        caption: "总览：先看外部不确定性如何进入程序，再看问题链条和防御工具怎样切断传播。",
        height: 1049,
        id: "overview",
        src: "/visual-notes/defensive-programming-robustness/01-overview.png",
        title: "01 总览图",
        width: 1499,
      },
      {
        alt: "正确性和健壮性对比图，区分规约内严格符合和异常情况下尽量可控。",
        caption: "概念对比：正确性关注规约内做对，健壮性关注规约之外仍保持可控。",
        height: 1049,
        id: "correctness-vs-robustness",
        src: "/visual-notes/defensive-programming-robustness/02-correctness-vs-robustness.png",
        title: "02 正确性和健壮性",
        width: 1499,
      },
      {
        alt: "软件问题链条图，展示 Mistake、Fault 或 Bug、Error、Failure，以及 Defect 和 Exception 的位置。",
        caption: "术语分层：主链条是 Mistake -> Fault(Bug) -> Error -> Failure，Defect 和 Exception 不应混入同一箭头链。",
        height: 1049,
        id: "problem-chain",
        src: "/visual-notes/defensive-programming-robustness/03-problem-chain.png",
        title: "03 软件中的问题链条",
        width: 1499,
      },
      {
        alt: "RIP 模型和 findLast 示例图，展示 Reachability、Infection、Propagation 如何共同导致 Failure。",
        caption: "RIP 模型：x=[] 未触达，n=3 触达但未感染，n=5 感染但未传播，n=1 才成为外部可见 failure。",
        height: 1024,
        id: "rip-model-findlast",
        src: "/visual-notes/defensive-programming-robustness/04-rip-model-findlast.png",
        title: "04 Fault 如何变成 Failure",
        width: 1536,
      },
      {
        alt: "防御性编程工具箱图，展示外部不可信数据、边界隔栏、输入检查、错误处理、断言、异常处理和智能指针。",
        caption: "工具箱：输入检查守边界；断言查内部不变量，尽量一条断言只查一个条件，并避免带副作用表达式。",
        height: 1049,
        id: "defensive-toolbox-barricade",
        src: "/visual-notes/defensive-programming-robustness/05-defensive-toolbox-barricade.png",
        title: "05 防御性编程工具箱",
        width: 1499,
      },
      {
        alt: "C++ 异常和资源安全对比图，展示手动 delete 被异常跳过导致内存泄漏，以及 RAII 和智能指针自动释放资源。",
        caption: "资源安全：异常会改变控制流；bad_alloc、out_of_range、invalid_argument 等标准异常应和 RAII、智能指针一起理解。",
        height: 1049,
        id: "cpp-exception-resource-safety",
        src: "/visual-notes/defensive-programming-robustness/06-cpp-exception-resource-safety.png",
        title: "06 C++ 异常与资源安全",
        width: 1499,
      },
      {
        alt: "提高健壮性的方法与权衡图，展示 Fault Avoidance、Fault Detection、Fault Tolerance 以及开发阶段、发布阶段和过度防御的取舍。",
        caption: "方法与权衡：防御性编程主要属于 Fault Avoidance；同时要理解 Fault Detection、Fault Tolerance，以及过度防御的成本。",
        height: 1024,
        id: "methods-and-tradeoffs",
        src: "/visual-notes/defensive-programming-robustness/07-methods-and-tradeoffs.png",
        title: "07 方法与权衡",
        width: 1536,
      },
    ],
  },
  {
    articleSlug: "current-workflow",
    description: "把个人工作流拆成从想法、任务、代码、验证到复盘的六个阶段，便于快速看清整套系统如何运转。",
    slug: "current-workflow",
    title: "我目前的工作流",
    images: [
      {
        alt: "当前工作流总览图，串联想法、Linear、Codex、GitHub、HomePage 和复盘。",
        caption: "总览：把从想法到产品、再到复盘的主链路压缩成一张图。",
        height: 1049,
        id: "overview",
        src: "/visual-notes/current-workflow/01-overview.png",
        title: "01 总览图",
        width: 1499,
      },
      {
        alt: "从 goal、规格、worker 到 PR 的任务推进流程图。",
        caption: "任务推进：先把目标说清楚，再让 worker 按边界产出可审查结果。",
        height: 1050,
        id: "goal-spec-worker-pr",
        src: "/visual-notes/current-workflow/02-goal-spec-worker-pr.png",
        title: "02 目标、规格、worker 与 PR",
        width: 1498,
      },
      {
        alt: "HomePage 发布与验证流程图，包含本地检查、构建和发布前确认。",
        caption: "站点链路：文章和页面进入 HomePage 后，需要经过检查、构建和可见性验证。",
        height: 1049,
        id: "homepage-validation",
        src: "/visual-notes/current-workflow/03-homepage-validation.png",
        title: "03 HomePage 验证链路",
        width: 1499,
      },
      {
        alt: "审计和修复循环图，展示发现问题、定位证据、提出修复和复查的过程。",
        caption: "审计修复：把问题留在可追踪记录里，再用受控修复闭环。",
        height: 1049,
        id: "audit-repair-loop",
        src: "/visual-notes/current-workflow/04-audit-repair-loop.png",
        title: "04 审计与修复循环",
        width: 1499,
      },
      {
        alt: "状态安全和知识沉淀图，展示文档、仓库、任务和学习记录的关系。",
        caption: "状态安全：用轻量记录降低上下文丢失和伪完成风险。",
        height: 1049,
        id: "state-safety-knowledge",
        src: "/visual-notes/current-workflow/05-state-safety-knowledge.png",
        title: "05 状态安全与知识沉淀",
        width: 1499,
      },
      {
        alt: "目标监控和纠偏图，展示长期目标、观察信号和人工判断入口。",
        caption: "监控纠偏：长期目标需要持续观察，也需要保留人工判断点。",
        height: 1050,
        id: "goal-monitoring-correction",
        src: "/visual-notes/current-workflow/06-goal-monitoring-correction.png",
        title: "06 目标监控与纠偏",
        width: 1498,
      },
    ],
  },
  {
    articleSlug: "native-goal-architecture-evolution",
    description: "用五张图像化笔记重组展示从人工 goal-loop 到原生 /goal supervisor 的架构演化。",
    slug: "native-goal",
    title: "从 goal-loop 到原生 /goal supervisor",
    images: [
      {
        alt: "从 goal-loop 到原生 /goal supervisor 总览图，展示旧结构循环、新结构层级和核心判断。",
        caption: "总览：从人工 goal-loop 转向原生 /goal supervisor 的整体架构演化。",
        height: 1050,
        id: "overview",
        src: "/visual-notes/native-goal/01-overview.png",
        title: "01 总览图",
        width: 1498,
      },
      {
        alt: "解释为什么需要 goal-loop，又为什么要离开它，包括长任务问题、goal-loop 价值和暴露出来的问题。",
        caption: "背景与问题：goal-loop 让长任务可观察，但脚本不该成为默认调度脑。",
        height: 1049,
        id: "why-goal-loop-failed",
        src: "/visual-notes/native-goal/02-why-goal-loop-failed.png",
        title: "02 旧结构的价值与边界",
        width: 1499,
      },
      {
        alt: "原生 /goal 后的新职责分配图，包含 Root Supervisor、Task Supervisor、Worker、Audit-only 和 Human export decision。",
        caption: "新结构：原生 /goal 保持目标，root supervisor 按语义组织 worker、audit 和人工判断。",
        height: 1049,
        id: "native-goal-architecture",
        src: "/visual-notes/native-goal/03-native-goal-architecture.png",
        title: "03 原生 /goal 后的新架构",
        width: 1499,
      },
      {
        alt: "两个关键取舍图，解释 dispatcher 降级为可选实验工具，以及 root supervisor 需要 validation 权。",
        caption: "设计取舍：取消默认 dispatcher，方向不清晰时先 validation，再 dispatch。",
        height: 1049,
        id: "dispatcher-validation-tradeoff",
        src: "/visual-notes/native-goal/04-dispatcher-validation-tradeoff.png",
        title: "04 dispatcher 与 validation",
        width: 1499,
      },
      {
        alt: "反思与后续约束图，展示失败提醒、弃用方向、开发约束、未决问题和后续连接。",
        caption: "反思与约束：少而清晰，先证据后行动，关键判断留给人。",
        height: 1049,
        id: "reflection-constraints",
        src: "/visual-notes/native-goal/05-reflection-constraints.png",
        title: "05 反思与后续约束",
        width: 1499,
      },
    ],
  },
  {
    articleSlug: "ai-foundations-cifar10-cnn-learning-record",
    description: "把 CIFAR-10 CNN 作业拆成任务、数据、模型、训练循环和结果概念，适合先看全局再回到代码细节。",
    slug: "cifar10-cnn",
    title: "CIFAR-10 CNN 训练记录",
    images: [
      {
        alt: "CIFAR-10 CNN 作业总览图，展示任务目标、训练流程、核心代码和学习收获。",
        caption: "总览：先把图像分类作业的目标、流程和关键概念放在同一张图里。",
        height: 1049,
        id: "overview",
        src: "/visual-notes/cifar10-cnn/01-overview.png",
        title: "01 总览图",
        width: 1499,
      },
      {
        alt: "数据来源和数据处理结构图，展示 CIFAR-10、DataLoader、标准化和增强流程。",
        caption: "数据入口：理解数据集、预处理和批次加载怎样进入训练过程。",
        height: 1050,
        id: "data-source-structure",
        src: "/visual-notes/cifar10-cnn/02-data-source-structure.png",
        title: "02 数据来源与结构",
        width: 1498,
      },
      {
        alt: "模型结构和特征图图解，展示卷积块、池化、BatchNorm 和分类层。",
        caption: "模型结构：CNN 先提取中间特征，再把特征送入分类层。",
        height: 1050,
        id: "model-feature-maps",
        src: "/visual-notes/cifar10-cnn/03-model-feature-maps.png",
        title: "03 模型与特征图",
        width: 1498,
      },
      {
        alt: "训练循环图，展示 forward、loss、backward、optimizer step 和评估。",
        caption: "训练循环：从前向计算到反向传播，再到参数更新和测试评估。",
        height: 1050,
        id: "training-loop",
        src: "/visual-notes/cifar10-cnn/04-training-loop.png",
        title: "04 训练循环",
        width: 1498,
      },
      {
        alt: "概念和结果整理图，包含准确率、CUDA、AdamW、随机种子和后续理解。",
        caption: "结果与概念：把训练结果和容易混淆的基础概念放在一起复盘。",
        height: 1049,
        id: "concepts-results",
        src: "/visual-notes/cifar10-cnn/05-concepts-results.png",
        title: "05 概念与结果",
        width: 1499,
      },
    ],
  },
  {
    articleSlug: "ai-foundations-transformer-learning-record",
    description: "围绕状态表示这条主线，把 Transformer 理解拆成 Q/K/V、embedding 与位置、多头关系视角、Decoder 前缀、代码 shape、实验边界和 H[-1] 到 logits[-1] 的完整预测链路。",
    slug: "transformer-nmt",
    title: "从 memory 到状态表示",
    images: [
      {
        alt: "Transformer 机器翻译学习总览图，展示从 RNN 记忆、自注意力、Decoder 前缀到作业代码和实验边界的理解路径。",
        caption: "总览：先看 RNN 直觉如何转向 Transformer，再把理解落到作业代码和未完成实验边界。",
        height: 1024,
        id: "overview",
        src: "/visual-notes/transformer-nmt/01-overview.png",
        title: "01 总览图",
        width: 1536,
      },
      {
        alt: "Self-Attention 的 Q/K/V 图，展示 X 投影成 Q、K、V，经相关性矩阵 A 得到上下文表示 H。",
        caption: "Q/K/V：参数跟表示维度有关，attention 矩阵是当前输入动态算出来的关系。",
        height: 1024,
        id: "qkv-attention",
        src: "/visual-notes/transformer-nmt/02-qkv-attention.png",
        title: "02 Q/K/V 与自注意力",
        width: 1536,
      },
      {
        alt: "Decoder 前缀预测图，对比训练验证中的 teacher forcing 和 translate 推理中的逐词生成。",
        caption: "Decoder：训练知道真实前缀并行算 loss，推理只能用已经生成的前缀预测下一个 token。",
        height: 1024,
        id: "decoder-prefix",
        src: "/visual-notes/transformer-nmt/03-decoder-prefix.png",
        title: "03 Decoder 前缀预测",
        width: 1536,
      },
      {
        alt: "nmt_de2en.py 中主要 Tensor 数据流图，展示 src、tgt、tgt_input、src_emb、memory、outs、logits 和 tgt_out 的 shape。",
        caption: "代码数据流：把 src/tgt 变成 embedding，经 Transformer 得到 logits，再和错开一位的 tgt_out 计算 loss。",
        height: 1024,
        id: "code-shapes",
        src: "/visual-notes/transformer-nmt/04-code-shapes.png",
        title: "04 作业代码中的 shape",
        width: 1536,
      },
      {
        alt: "Encoder 和 Decoder 职责分工图，展示 Encoder 使用 src_emb 输出 memory，Decoder 使用 tgt_emb 和 memory。",
        caption: "职责分工：Encoder 读源语言并输出 memory，Decoder 读目标前缀并通过 cross-attention 对齐源语言信息。",
        height: 1024,
        id: "encoder-decoder",
        src: "/visual-notes/transformer-nmt/05-encoder-decoder.png",
        title: "05 Encoder 与 Decoder",
        width: 1536,
      },
      {
        alt: "Transformer 作业实验边界图，展示删除 EOS、Embedding 最近邻、Temperature 和 Tiny Base Wide 超参数实验。",
        caption: "实验边界：已能写实验设计和观察指标；参数训练未完成前，不提前总结 Tiny/Base/Wide 效果。",
        height: 1024,
        id: "experiment-boundary",
        src: "/visual-notes/transformer-nmt/06-experiment-boundary.png",
        title: "06 实验边界",
        width: 1536,
      },
      {
        alt: "Transformer 一次预测链路图，展示源句经过 Encoder 得到 memory，目标前缀经过 Decoder 得到 H，取 H[-1] 投影成 logits[-1] 并生成下一个 token。",
        caption: "完整预测链路：H[-1] 不是 token，而是目标前缀和 memory 融合后的最后位置状态；generator 再把它投影到词表得到 logits[-1]。",
        height: 1024,
        id: "prediction-flow",
        src: "/visual-notes/transformer-nmt/07-prediction-flow.png",
        title: "07 从 memory 到 logits[-1]",
        width: 1536,
      },
      {
        alt: "Embedding 和位置编码图，展示 token id 查询 embedding 表，token embedding 与 position 相加形成初始状态，并由最终 loss 反向传播更新 embedding 表。",
        caption: "Embedding 与位置：embedding 表是可训练参数；位置让语境不是一袋词，最终 loss 会反向传播塑形这张表。",
        height: 1024,
        id: "embedding-position",
        src: "/visual-notes/transformer-nmt/08-embedding-position.png",
        title: "08 Embedding 与位置",
        width: 1536,
      },
      {
        alt: "多头和多层 attention 图，展示单个 head 的二元关系、多个 head 并行形成多套关系视角、多层状态继续交互，以及最终 loss 反向传播到各个 head。",
        caption: "多头与多层：单次 attention 是二元关系；多头和多层让复杂关系折叠进 hidden state，head 不单独算 loss。",
        height: 1024,
        id: "multihead-layers",
        src: "/visual-notes/transformer-nmt/09-multihead-layers.png",
        title: "09 多头与多层",
        width: 1536,
      },
    ],
  },
  {
    articleSlug: "aigc-music-exploration-record",
    description: "把 AIGC 音乐探索拆成基本流程、提示词工具、Suno 操作、工作流固化和表达边界。",
    slug: "aigc-music",
    title: "AIGC 音乐探索记录",
    images: [
      {
        alt: "AIGC 音乐探索总览图，展示从兴趣出发到工具试用、工作流和边界反思。",
        caption: "总览：从想生成一段旋律开始，看清 AIGC 音乐探索的主线。",
        height: 1049,
        id: "overview",
        src: "/visual-notes/aigc-music/01-overview.png",
        title: "01 总览图",
        width: 1499,
      },
      {
        alt: "AIGC 音乐 prompt 和工具图，展示情绪、场景、风格和声音元素如何进入提示词。",
        caption: "提示词与工具：先描述想听到什么，再用工具生成多个版本。",
        height: 1050,
        id: "prompt-tools",
        src: "/visual-notes/aigc-music/02-prompt-tools.png",
        title: "02 Prompt 与工具",
        width: 1498,
      },
      {
        alt: "Suno 浏览器工作流图，展示进入工具、填写提示、生成和筛选的过程。",
        caption: "Suno 操作：把浏览器里的生成流程拆成可重复的步骤。",
        height: 1050,
        id: "suno-browser-workflow",
        src: "/visual-notes/aigc-music/03-suno-browser-workflow.png",
        title: "03 Suno 浏览器流程",
        width: 1498,
      },
      {
        alt: "music-creator 工作流图，展示如何把个人经历转成音乐生成任务。",
        caption: "工作流固化：把一次探索沉淀成可复用的 music-creator 方法。",
        height: 1049,
        id: "music-creator-workflow",
        src: "/visual-notes/aigc-music/04-music-creator-workflow.png",
        title: "04 music-creator 工作流",
        width: 1499,
      },
      {
        alt: "表达边界图，展示复杂私人情绪、随机生成和可控表达之间的关系。",
        caption: "表达边界：复杂情绪可以提供方向，但不能期待随机生成完全替代表达。",
        height: 1049,
        id: "expression-boundary",
        src: "/visual-notes/aigc-music/05-expression-boundary.png",
        title: "05 表达边界",
        width: 1499,
      },
    ],
  },
  {
    articleSlug: "attention-memory-development-record",
    description: "把 Attention Memory 的起点、项目记忆约定、目标归档生命周期、测试和后续判断整理成五张图。",
    slug: "attention-memory",
    title: "Attention Memory 开发记录",
    images: [
      {
        alt: "Attention Memory 开发记录总览图，展示问题起点、方案收敛、发布和反思。",
        caption: "总览：从 MCP memory 疑问走向 prompt-only 项目记忆约定。",
        height: 1050,
        id: "overview",
        src: "/visual-notes/attention-memory/01-overview.png",
        title: "01 总览图",
        width: 1498,
      },
      {
        alt: "从 MCP 到最小文件记忆方案的图，展示 goal.md、memory.md 和 memory.archive.md 的职责。",
        caption: "最小文件：让记忆跟随注意力行动，而不是依赖一个笨重 memory server。",
        height: 1049,
        id: "mcp-to-minimal-files",
        src: "/visual-notes/attention-memory/02-mcp-to-minimal-files.png",
        title: "02 从 MCP 到最小文件",
        width: 1499,
      },
      {
        alt: "目标和归档生命周期图，展示 goal 变化、memory 审查和 archive 冷存储。",
        caption: "生命周期：goal 改变时才审查归档，普通任务不翻冷存储。",
        height: 1049,
        id: "goal-archive-lifecycle",
        src: "/visual-notes/attention-memory/03-goal-archive-lifecycle.png",
        title: "03 目标与归档生命周期",
        width: 1499,
      },
      {
        alt: "测试和最终形态图，展示仓库发布、规则检查和轻量工作流边界。",
        caption: "测试与形态：把规则写小、跑通、发布，再继续观察实际使用。",
        height: 1049,
        id: "tests-final-shape",
        src: "/visual-notes/attention-memory/04-tests-final-shape.png",
        title: "04 测试与最终形态",
        width: 1499,
      },
      {
        alt: "判断和未来方向图，展示记忆规则、认知偏差提醒和后续可扩展方向。",
        caption: "判断未来：先保留最小约束，再根据真实任务决定是否扩展。",
        height: 1049,
        id: "judgement-future",
        src: "/visual-notes/attention-memory/05-judgement-future.png",
        title: "05 判断与未来方向",
        width: 1499,
      },
    ],
  },
  {
    articleSlug: "http-api-git-push",
    description: "把 HTTP、API、客户端服务器分工和 Git Smart HTTP 推送过程整理成六张图，帮助先建立网络请求全局图。",
    slug: "http-api-git-push",
    title: "从 HTTP、API 到 git push",
    images: [
      {
        alt: "HTTP、API 和 git push 总览图，展示从 Web API 到 Git Smart HTTP 的理解路径。",
        caption: "总览：从一个 Web API 作业出发，逐步理解 HTTP、API 和 git push。",
        height: 992,
        id: "overview",
        src: "/visual-notes/http-api-git-push/01-overview.png",
        title: "01 总览图",
        width: 1586,
      },
      {
        alt: "HTTP 报文和方法图，展示请求行、请求头、请求体、响应和常见方法。",
        caption: "HTTP 基础：方法和报文格式是通用协议层，具体路径由服务器定义。",
        height: 992,
        id: "http-message-methods",
        src: "/visual-notes/http-api-git-push/02-http-message-methods.png",
        title: "02 HTTP 报文与方法",
        width: 1586,
      },
      {
        alt: "客户端、服务器和 API 的关系图，展示请求、路径、参数、处理逻辑和响应。",
        caption: "客户端与服务器：API 不是远程函数本身，而是服务器公开的请求入口。",
        height: 992,
        id: "client-server-api",
        src: "/visual-notes/http-api-git-push/03-client-server-api.png",
        title: "03 客户端、服务器与 API",
        width: 1586,
      },
      {
        alt: "git push Smart HTTP 流程图，展示发现远端、认证、打包和 receive-pack。",
        caption: "Git Smart HTTP：git push 会通过 HTTP 协议协商、认证并上传 packfile。",
        height: 992,
        id: "git-push-smart-http",
        src: "/visual-notes/http-api-git-push/04-git-push-smart-http.png",
        title: "04 git push Smart HTTP",
        width: 1586,
      },
      {
        alt: "HTTPS 推送细节图，展示 TLS、凭据、Authorization 和 GitHub 远端处理。",
        caption: "HTTPS 细节：传输层保护连接，凭据和权限决定远端是否接受更新。",
        height: 992,
        id: "https-push-details",
        src: "/visual-notes/http-api-git-push/05-https-push-details.png",
        title: "05 HTTPS 推送细节",
        width: 1586,
      },
      {
        alt: "Smart HTTP 和 REST API 对比图，展示二者都跑在 HTTP 上但语义不同。",
        caption: "概念对比：Smart HTTP 是 Git 协议的 HTTP 传输，REST API 是业务接口风格。",
        height: 992,
        id: "smart-http-vs-rest-api",
        src: "/visual-notes/http-api-git-push/06-smart-http-vs-rest-api.png",
        title: "06 Smart HTTP 与 REST API",
        width: 1586,
      },
    ],
  },
  {
    description: "把 MIT Missing Semester 第 1 讲 Shell 入门整理成九张复习图，覆盖 Shell 定位、命令解析、PATH、数据流、工具流水线、Bash 脚本和进程并行。",
    slug: "missing-semester-shell",
    title: "Missing Semester 01：Shell 入门",
    images: [
      {
        alt: "Shell 的定位图，展示 Shell 作为命令解释器、组合语言、执行环境和开放工具箱。",
        caption: "定位：Shell 不是封闭命令大全，而是调用工具、组合数据流的开放执行环境。",
        height: 1050,
        id: "shell-positioning",
        src: "/visual-notes/missing-semester-shell/01-shell-positioning.png",
        title: "01 Shell 的定位",
        width: 1498,
      },
      {
        alt: "命令解析与位置感图，展示 Shell 如何拆分命令参数，并用绝对路径、相对路径和特殊目录符号定位文件。",
        caption: "命令解析：Shell 先拆词和定位，再把参数列表交给程序。",
        height: 1049,
        id: "command-parsing-paths",
        src: "/visual-notes/missing-semester-shell/02-command-parsing-paths.png",
        title: "02 命令解析与位置感",
        width: 1499,
      },
      {
        alt: "PATH、环境变量与内建命令图，展示 $PATH 读取、外部命令查找和 cd 作为内建命令改变当前 Shell 状态。",
        caption: "PATH 与内建：PATH 告诉 Shell 去哪里找外部命令，内建命令改变 Shell 自己的状态。",
        height: 1050,
        id: "path-env-builtins",
        src: "/visual-notes/missing-semester-shell/03-path-env-builtins.png",
        title: "03 PATH、环境变量与内建命令",
        width: 1498,
      },
      {
        alt: "数据流与组合图，展示 stdin、stdout、stderr、重定向、管道、tee 和命令替换的关系。",
        caption: "数据流：重定向改变去向，管道连接程序，tee 复制数据流。",
        height: 1049,
        id: "dataflow-composition",
        src: "/visual-notes/missing-semester-shell/04-dataflow-composition.png",
        title: "04 数据流与组合",
        width: 1499,
      },
      {
        alt: "文本与文件工具流水线图，展示 find、cat、head、tail、grep、sed、awk、sort、uniq 在流水线中的分工。",
        caption: "工具流水线：重点不是背参数，而是知道每个工具站在数据处理的哪一环。",
        height: 1049,
        id: "text-file-pipeline",
        src: "/visual-notes/missing-semester-shell/05-text-file-pipeline.png",
        title: "05 文本与文件工具流水线",
        width: 1499,
      },
      {
        alt: "Bash 作为自动化语言图，展示 Bash 调用外部程序，并通过退出状态、if、&&、|| 控制流程。",
        caption: "Bash 语言观：Bash 更像自动化胶水，常用命令是否成功来决定流程。",
        height: 1049,
        id: "bash-automation-language",
        src: "/visual-notes/missing-semester-shell/06-bash-automation-language.png",
        title: "06 Bash 作为自动化语言",
        width: 1499,
      },
      {
        alt: "脚本成为工具图，展示 shebang、chmod +x、执行权限、脚本参数和严格模式。",
        caption: "脚本工具化：带参数、带权限、带失败策略的脚本，就是自己的小工具。",
        height: 1049,
        id: "script-as-tool",
        src: "/visual-notes/missing-semester-shell/07-script-as-tool.png",
        title: "07 脚本成为工具",
        width: 1499,
      },
      {
        alt: "进程与并行图，展示后台任务、wait、kill、xargs -P、进程替换和管道并发。",
        caption: "并行：不只是 &，批量限并发、进程替换和管道也会让多个程序同时工作。",
        height: 1049,
        id: "process-parallelism",
        src: "/visual-notes/missing-semester-shell/08-process-parallelism.png",
        title: "08 进程与并行",
        width: 1499,
      },
      {
        alt: "能力索引与练习选择图，展示从学习目标到 Shell 能力，再到优先练习的映射。",
        caption: "复习抓手：先问目标，再找能力，再选最小练习。",
        height: 1049,
        id: "capability-index-practice",
        src: "/visual-notes/missing-semester-shell/09-capability-index-practice.png",
        title: "09 能力索引与练习选择",
        width: 1499,
      },
    ],
  },
];

export function getAllVisualNotes() {
  return visualNotes;
}

export function getVisualNoteBySlug(slug: string) {
  return visualNotes.find((note) => note.slug === slug) ?? null;
}

export function getVisualNoteByArticleSlug(articleSlug: string) {
  return visualNotes.find((note) => note.articleSlug === articleSlug) ?? null;
}
